functional:
  - Пользователь должен иметь возможность начать игру без регистрации и авторизации
  - Пользователь должен иметь возможность зарегистрироваться/авторизоваться по электронной почте
  - Пользователь должен иметь возможность зарегистрироваться/авторизоваться по аккаунту GitHub
  - Пользователь должен иметь возможность зарегистрироваться/авторизоваться по аккаунту Discord
  - Пользователь должен иметь возможность выбрать язык, на котором будет проходить соревнование
  - В Личном кабинете пользователь должен иметь возможность создать игру по настраиваемым параметрам (выбрать уровень сложности, время игры, соперник, тематику задания)
  - В Личном кабинете пользователь должен иметь возможность присоедениться к уже созданным играм/турнирам
  - Пользователь должен иметь возможность создать игру с ботом
  - Пользователь должен иметь возможность создать игру со случайным пользователем
  - Пользователь должен иметь возможность создать игру с конкретным пользователем
  - На странице игры должен быть реализован встроенный редактор кода
  - В режиме игры должен быть реализован чат  для участников соревнования
  - Должна быть реализована автоматическая проверка решения участников соревнования
  - Должна быть реализована возможность очистить редактор кода
  - Пользователь должен иметь возможнность переиграть задание при проигрыше
  - История игр пользователя должна сохранятся только для авторизованных премиум-пользователей
  - Должен быть реализован таймер выполнения задания, после которого игра завершается
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть. Первый в любой момент игры, пока она не закончена, может переподключиться в игру.
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры.
  - Победитель-игрок может выйти из игры по нажатию кнопки "exit", которая у него появляется
  - Проигравший игрок должен иметь возможность доиграть при проигрыше
  - В личном кабинете должен  быть реализован чат для общения со всеми пользователями
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь адаптивную верстку
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Оба пользователя должны видеть два редактора, слева - свой редактор, справа - соперника.
  - Наверху находится время игры и ниже - задание .
  - Каждый игрок должен видеть код своего соперника в режиме он-лайн.
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть. Первый в любой момент игры, пока она не закончена, может переподключиться в игру.
  - После проигрыша/выигрыша пользователь должен увидеть информацию о результате
  - В Личном кабинете должна отображаться статистика игр пользователя
implicit:
  - Пользователь должен иметь возможность сменить язык сайта, т.к. преимущественная аудитория - русская
  - Должна собираться статистика по результатм игр авторизованного игрока
  - Игрок должен иметь возможность выйти из личного кабинета кабинета
  - При вводе данных несуществующего пользователя должна появляться ифнормация об ошибке авторизации
